######################################################################
# Automatically generated by qmake (3.0) mar. d�c. 5 11:10:08 2017
######################################################################

TEMPLATE = app
TARGET = projet_cpoa
INCLUDEPATH += .
QT += core gui widgets

# Input
HEADERS += header.hpp mainwindow.h
FORMS += mainwindow.ui
SOURCES +=  main.cpp \
    mainwindow.cpp
